version: '3'

services:
  go-api-template:
    build: .
    depends_on:
      - mongo
    volumes:
      - ${PWD}/config.yaml:/config.yaml
    ports:
      - "8000:8000"

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
